# TLS Secret
# TODOS:
#   - replace %__secret_name__% with the name of this secret
#   - replace %__secret_namespace__% with the namespace ths secret should exist in
#   - replace %__base64_encoded_key__% with the Base64-encoded key
#   - replace %__base64_encoded_cert__% with the Base64-encoded certificate

kind: Secret
apiVersion: v1
metadata:
  name: %__secret_name__%
  namespace: %__secret_namespace__%
type: kubernetes.io/tls
data:
  tls.key: %__base64_encoded_key__%
  tls.crt: %__base64_encoded_cert__%
