# Basic Auth information for Iron Functions API protection
# REFERENCES:
#   - https://github.com/iron-io/functions/tree/master/docs/operating/kubernetes/kubernetes-production
# TODOS:
#   - replace %__ironfx_namespace__% with the namespace for the Iron Functions API
#   - replace %__basic_auth_string__% with the Basic Auth file contents (generate with htpasswd -c auth [username])

kind: Secret
apiVersion: v1
metadata:
  name: ironfx-ui-authentication
  namespace: %__ironfx_namespace__%
data:
  auth: %__basic_auth_string__%
  # generate the above with htpasswd -c auth [user]