version: "3"
services:
  iron-functions:
    image: iron/functions:latest
    ports:
      - "8080:8080"
    volumes:
      - "./data:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.4'
          memory: 80M
  iron-functions-ui:
    image: iron/functions-ui:latest
    entrypoint: [ "npm", "start" ]
    environment:
      - API_URL=http://iron-functions:8080
    ports:
      - "4000:4000"
    volumes:
      - "./data-ui:/app/data"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.4'
          memory: 80M
  docker-registry:
    image: registry:2
    volumes:
      - "./data-registry:/var/lib/registry"
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.4'
          memory: 80M