version: "3"
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "default_root_password"
      MYSQL_DATABASE: "default_db"
      MYSQL_USER: "default_user"
      MYSQL_PASSWORD: "default_password"
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
        reservations:
          cpus: '0.4'
          memory: 100M