apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: default
  labels:
    app: mysql
    env: production
    type: credentials
data:
  MYSQL_ROOT_PASSWORD: default_root_password
  MYSQL_DATABASE: default_db
  MYSQL_USER: default_user
  MYSQL_PASSWORD: default_password