apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
    env: production
    type: database
spec:
  selector:
    app: mysql
    env: production
    type: database
  ports:
  - port: 3306
    targetPort: 3306